-- Schema used by the application. Apply only to a new database; the connected
-- Supabase project already has these tables and was not changed by this file.
-- Reference data belongs in observations_or_reference and must come from a
-- station or a documented reanalysis source.

create table if not exists public.locations (
  id text primary key,
  name text not null,
  level text not null check (level in ('state', 'district', 'city')),
  parent_id text references public.locations(id),
  lat double precision,
  lon double precision,
  region_code text,
  state_code text,
  created_at timestamptz not null default now()
);

create table if not exists public.forecast_runs (
  id uuid primary key default gen_random_uuid(),
  model text not null,
  run_time timestamptz,
  fetched_at timestamptz not null default now(),
  source text not null
);

create table if not exists public.forecast_points (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.forecast_runs(id) on delete cascade,
  location_id text not null references public.locations(id),
  valid_time timestamptz not null,
  lead_hours integer not null,
  rainfall_mm double precision,
  temp_c double precision,
  wind_speed_kmh double precision,
  wind_dir_deg double precision,
  created_at timestamptz not null default now()
);

create table if not exists public.observations_or_reference (
  id bigint generated by default as identity primary key,
  location_id text not null references public.locations(id),
  valid_time timestamptz not null,
  rainfall_mm double precision,
  temp_c double precision,
  wind_speed_kmh double precision,
  source_type text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.model_metrics (
  id bigint generated by default as identity primary key,
  location_id text references public.locations(id),
  model text not null,
  variable text not null,
  lead_time integer not null,
  start_date date,
  end_date date,
  mae double precision,
  rmse double precision,
  corr double precision,
  bias double precision,
  updated_at timestamptz not null default now()
);

create table if not exists public.model_weights (
  id bigint generated by default as identity primary key,
  location_id text references public.locations(id),
  variable text not null,
  lead_time integer not null,
  generated_at timestamptz not null default now(),
  model text not null,
  weight double precision not null,
  method text not null
);

create table if not exists public.risk_events (
  id bigint generated by default as identity primary key,
  location_id text references public.locations(id),
  valid_time timestamptz,
  risk_type text not null,
  level text not null,
  score double precision,
  source text not null,
  created_at timestamptz not null default now()
);

create index if not exists forecast_points_location_valid_idx
  on public.forecast_points (location_id, valid_time);
create index if not exists observations_location_valid_idx
  on public.observations_or_reference (location_id, valid_time);
create index if not exists model_metrics_location_variable_lead_idx
  on public.model_metrics (location_id, variable, lead_time);
